version: '3'

services:

  #DJANGO
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    working_dir: /code
    # tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    networks:
      - my-network

  #REDIS
  redis:
    image: redis:5.0.7
    container_name: redisdj
    # tty: true
    volumes:
      - redisdj:/data
    networks:
      - my-network

  #POSTGRES
  postgres:
    image: postgres:12.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: django_drf_pg4
    # tty: true
    ports:
      - "54321:5432"
    networks:
      - my-network

#CONFIGURATION
networks:
  my-network:
    driver: bridge

volumes:
  dbdata:
  redisdj:

volumes:
  dbdata:
    driver: local
  redisdj:
    driver: local