# Generated by Django 3.0.2 on 2020-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('name_service', models.CharField(max_length=200)),
                ('type_service', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=7)),
            ],
        ),
    ]
